esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  
wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} AP
    password: !secret esphome_fallback_ap_password
    
web_server:
  port: 80
captive_portal:
# Enable logging
logger:
# Enable Home Assistant API
api:
ota:
  - platform: esphome

sensor:
  - platform: wifi_signal
    name: WiFi Strength
    update_interval: 120s
  - platform: uptime
    name: Uptime
    update_interval: 60s

time:
  - platform: homeassistant
    id: homeassistant_time