substitutions:
  device_name: "childroom-desk-lightswitch"
  friendly_name: "Chilroom desk lightswitch"
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"

packages:
  base: !include .base.yaml

esphome:
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y

output:
  - platform: gpio
    id: relay_output
    pin: GPIO5

switch:
  - platform: output
    id: relay
    name: "${device_name} Relay"
    output: relay_output

binary_sensor:
  - platform: gpio
    name: "${device_name} Switch"
    pin: GPIO4
    on_press:
      then:
        - switch.toggle: relay
    filters:
      - delayed_on_off: 30ms

status_led:
  pin:
    number: GPIO0
    inverted: true

bluetooth_proxy:
  active: true
