substitutions:
  device_name: groundhall-lightswitch
  friendly_name: "Chodba přízemí vypínač světla"

packages:
  base: !include .base.yaml

esphome:
  name: ${device_name}
esp8266:
  board: esp01_1m

binary_sensor:
  - platform: gpio
    name: ${device_name} Button 1
    pin:
      number: GPIO4
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 20ms

  - platform: gpio
    name: ${device_name} Button 2
    pin:
      number: GPIO5
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 20ms